// <auto-generated />
using DCBStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCBStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615063608_SeedProductData")]
    partial class SeedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCBStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop doanh nhân mạnh mẽ, bền bỉ.",
                            ImageUrl = "/images/laptop-thinkpad.jpg",
                            Name = "Laptop ThinkPad T14",
                            Price = 25000000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cuốn sách bán chạy nhất mọi thời đại của Paulo Coelho.",
                            ImageUrl = "/images/nha-gia-kim.jpg",
                            Name = "Tiểu thuyết 'Nhà Giả Kim'",
                            Price = 69000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hương thơm cổ điển và quyến rũ cho phái nữ.",
                            ImageUrl = "/images/chanel-no5.jpg",
                            Name = "Nước hoa Chanel No. 5",
                            Price = 3500000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tai nghe chống ồn chủ động hàng đầu thế giới.",
                            ImageUrl = "/images/sony-headphone.jpg",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 8500000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
